name: Daily Data Collection

on:
  schedule:
    # 每天北京时间 10:30 运行（UTC 02:30）
    - cron: '30 2 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch hero data
        run: |
          node -e '
          const axios = require("axios");
          const fs = require("fs");
          const path = require("path");

          function getCurrentSeason() {
            const seasonsPath = path.join("data", "seasons.json");
            const seasons = JSON.parse(fs.readFileSync(seasonsPath, "utf8")).seasons;
            const today = new Date();
            
            for (const season of seasons) {
              const startDate = new Date(season.start_date);
              const endDate = season.end_date ? new Date(season.end_date) : new Date("9999-12-31");
              
              if (today >= startDate && today <= endDate) {
                return season.season;
              }
            }
            
            return seasons[seasons.length - 1].season; // 默认返回最新赛季
          }

          function updateMergedData(newData, date) {
            const mergedFilePath = path.join("data", "merged_data.json");
            let mergedData = {};

            // 如果合并文件存在，读取现有数据
            if (fs.existsSync(mergedFilePath)) {
              mergedData = JSON.parse(fs.readFileSync(mergedFilePath, "utf8"));
            }

            // 更新或添加当天的数据
            mergedData[date] = newData;

            // 写入合并后的数据
            fs.writeFileSync(mergedFilePath, JSON.stringify(mergedData, null, 2));
            console.log(`Updated merged data file with data for ${date}`);
          }

          async function fetchData() {
            try {
              const currentSeason = getCurrentSeason();
              console.log(`Using season: ${currentSeason}`);

              const response = await axios.get("https://webapi.blizzard.cn/ow-armory-server/hero_leaderboard", {
                params: {
                  game_mode: "jingji",
                  season: currentSeason,
                  mmr: "-127"
                },
                headers: {
                  "accept": "application/json",
                  "origin": "https://ow.blizzard.cn",
                  "referer": "https://ow.blizzard.cn/"
                }
              });

              const date = new Date().toISOString().split("T")[0];
              const dataDir = path.join("data", "daily");
              const filePath = path.join(dataDir, `${date}.json`);
              
              if (!fs.existsSync(dataDir)) {
                fs.mkdirSync(dataDir, { recursive: true });
              }

              // 添加时间戳和赛季信息，确保数据幂等性
              const dataToSave = {
                timestamp: new Date().toISOString(),
                season: currentSeason,
                data: response.data
              };

              fs.writeFileSync(filePath, JSON.stringify(dataToSave, null, 2));
              console.log(`Successfully collected data for ${date} (Season ${currentSeason})`);

              // 更新合并数据文件
              updateMergedData(dataToSave, date);
            } catch (error) {
              console.error("Error fetching data:", error.message);
              process.exit(1);
            }
          }

          fetchData();
          '

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/daily/ data/merged_data.json
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update hero data $(date +'%Y-%m-%d')"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          )