name: Daily Data Collection

on:
  schedule:
    # 每天北京时间 10:30 运行（UTC 02:30）
    - cron: '30 2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch hero data
        run: |
          node -e '
          const axios = require("axios");
          const fs = require("fs");
          const path = require("path");

          async function fetchData() {
            try {
              const response = await axios.get("https://webapi.blizzard.cn/ow-armory-server/hero_leaderboard", {
                params: {
                  game_mode: "jingji",
                  season: "15",
                  mmr: "-127"
                },
                headers: {
                  "accept": "application/json",
                  "origin": "https://ow.blizzard.cn",
                  "referer": "https://ow.blizzard.cn/"
                }
              });

              const date = new Date().toISOString().split("T")[0];
              const dataDir = path.join("data", "daily");
              
              if (!fs.existsSync(dataDir)) {
                fs.mkdirSync(dataDir, { recursive: true });
              }

              fs.writeFileSync(
                path.join(dataDir, `${date}.json`),
                JSON.stringify(response.data, null, 2)
              );

              console.log(`Successfully collected data for ${date}`);
            } catch (error) {
              console.error("Error fetching data:", error.message);
              process.exit(1);
            }
          }

          fetchData();
          '

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/daily/
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update hero data $(date +'%Y-%m-%d')"
            git push
          )